name: cellcharter-env
channels:
  - pytorch
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - archspec=0.2.3
  - blas=1.0
  - boltons=24.0.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - conda=24.3.0
  - conda-libmamba-solver=24.1.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - cudatoolkit=11.6.2
  - distro=1.9.0
  - ffmpeg=4.3
  - fmt=10.2.1
  - freetype=2.12.1
  - gmp=6.3.0
  - gnutls=3.6.13
  - icu=73.2
  - idna=3.7
  - intel-openmp=2023.1.0
  - jpeg=9e
  - jsonpatch=1.33
  - jsonpointer=2.4
  - keyutils=1.6.1
  - krb5=1.21.2
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libarchive=3.7.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.7.1
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libhwloc=2.10.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libpng=1.6.43
  - libsolv=0.7.28
  - libsqlite=3.45.3
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libtiff=4.5.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxml2=2.12.6
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.5.8
  - menuinst=2.0.2
  - mkl=2023.1.0
  - ncurses=6.4.20240210
  - nettle=3.6
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.2.1
  - packaging=24.0
  - pillow=9.4.0
  - pip=24.0
  - platformdirs=4.2.0
  - pluggy=1.5.0
  - pthread-stubs=0.4
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.10.14
  - python_abi=3.10
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - readline=8.2
  - reproc=14.2.4.post0
  - reproc-cpp=14.2.4.post0
  - requests=2.31.0
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - setuptools=69.5.1
  - tbb=2021.12.0
  - tk=8.6.13
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm=4.66.2
  - truststore=0.8.0
  - typing_extensions=4.11.0
  - wheel=0.43.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml-cpp=0.8.0
  - zlib=1.2.13
  - zstandard=0.22.0
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - affine==2.4.0
      - aiobotocore==2.5.4
      - aiohttp==3.9.5
      - aioitertools==0.11.0
      - aiosignal==1.3.1
      - anndata==0.10.7
      - anyio==4.3.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - array-api-compat==1.6
      - arrow==1.3.0
      - asciitree==0.3.3
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.2.0
      - babel==2.14.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - botocore==1.31.17
      - cellcharter==0.2.0
      - chex==0.1.86
      - click==8.1.7
      - click-plugins==1.1.1
      - cligj==0.7.2
      - cloudpickle==3.0.0
      - colorcet==3.1.0
      - comm==0.2.2
      - contextlib2==21.6.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - dask==2024.2.1
      - dask-image==2023.8.1
      - datashader==0.16.1
      - debugpy==1.8.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - distributed==2024.2.1
      - docrep==0.3.2
      - et-xmlfile==1.1.0
      - etils==1.7.0
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - fasteners==0.19
      - fastjsonschema==2.19.1
      - fiona==1.9.6
      - fire==0.6.0
      - flax==0.8.2
      - fonttools==4.51.0
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2023.6.0
      - geojson==3.1.0
      - geopandas==0.14.3
      - h11==0.14.0
      - h5py==3.11.0
      - harmonypy==0.0.9
      - httpcore==1.0.5
      - httpx==0.27.0
      - imageio==2.34.1
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - inflect==7.2.0
      - iniconfig==2.0.0
      - ipykernel==6.29.4
      - ipynb-path==0.1.5
      - ipython==8.23.0
      - isoduration==20.11.0
      - jax==0.4.26
      - jaxlib==0.4.26+cuda12.cudnn89
      - jedi==0.19.1
      - jinja2==3.1.3
      - jmespath==1.0.1
      - joblib==1.4.0
      - json5==0.9.25
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.1
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.1.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.0
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - legacy-api-wrap==1.4
      - lightkit==0.5.0
      - lightning-utilities==0.11.2
      - llvmlite==0.42.0
      - locket==1.0.0
      - magic-impute==3.0.0
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - matplotlib-inline==0.1.7
      - matplotlib-scalebar==0.8.1
      - mdurl==0.1.2
      - mistune==3.0.2
      - ml-collections==0.1.1
      - ml-dtypes==0.4.0
      - more-itertools==10.2.0
      - msgpack==1.0.8
      - mudata==0.2.3
      - multidict==6.0.5
      - multipledispatch==1.0.0
      - multiscale-spatial-image==0.11.2
      - natsort==8.4.0
      - nbclient==0.10.0
      - nbconvert==7.16.3
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - notebook==7.1.3
      - notebook-shim==0.2.4
      - numba==0.59.1
      - numcodecs==0.12.1
      - numpy==1.23.4
      - numpyro==0.14.0
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvcc-cu12==12.4.131
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==8.9.7.29
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - ome-zarr==0.8.3
      - omnipath==1.0.8
      - openpyxl==3.1.2
      - opt-einsum==3.3.0
      - optax==0.2.2
      - orbax-checkpoint==0.5.10
      - overrides==7.7.0
      - pandas==2.0.3
      - pandocfilters==1.5.1
      - param==2.1.0
      - parso==0.8.4
      - partd==1.4.1
      - patsy==0.5.6
      - pexpect==4.9.0
      - pims==0.6.1
      - pooch==1.8.1
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.43
      - protobuf==5.26.1
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==16.0.0
      - pycave==3.2.1
      - pyct==0.5.0
      - pygeos==0.14
      - pygments==2.17.2
      - pymde==0.1.18
      - pynndescent==0.5.12
      - pyparsing==3.1.2
      - pyproj==3.6.1
      - pyro-api==0.1.2
      - pyro-ppl==1.8.6
      - pytest==8.2.0
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - pytorch-lightning==1.9.5
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==26.0.2
      - rasterio==1.3.10
      - referencing==0.34.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - rpds-py==0.18.0
      - s3fs==2023.6.0
      - scanpy==1.10.1
      - scdrs==1.0.2
      - scikit-image==0.23.2
      - scikit-learn==1.4.2
      - scikit-misc==0.3.1
      - scipy==1.13.0
      - scprep==1.2.3
      - scvi-tools==0.20.3
      - seaborn==0.13.2
      - send2trash==1.8.3
      - session-info==1.0.0
      - shapely==2.0.4
      - six==1.16.0
      - sknw==0.15
      - slicerator==1.1.0
      - sniffio==1.3.1
      - snuggs==1.4.7
      - sortedcontainers==2.4.0
      - soupsieve==2.5
      - spatial-image==0.3.0
      - spatialdata==0.1.2
      - spatialdata-plot==0.2.1
      - squidpy==1.4.1
      - stack-data==0.6.3
      - statsmodels==0.14.2
      - stdlib-list==0.10.0
      - tblib==3.0.0
      - tensorstore==0.1.56
      - termcolor==2.4.0
      - terminado==0.18.1
      - threadpoolctl==3.4.0
      - tifffile==2024.4.18
      - tinycss2==1.2.1
      - tomli==2.0.1
      - toolz==0.12.1
      - torchmetrics==0.11.4
      - tornado==6.4
      - traitlets==5.14.3
      - typeguard==4.2.1
      - types-python-dateutil==2.9.0.20240316
      - tzdata==2024.1
      - umap-learn==0.5.6
      - uri-template==1.3.0
      - urllib3==1.26.18
      - validators==0.28.1
      - wcwidth==0.2.13
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - xarray==2023.12.0
      - xarray-dataclasses==1.7.0
      - xarray-datatree==0.0.14
      - xarray-schema==0.0.3
      - xarray-spatial==0.3.7
      - yarl==1.9.4
      - zarr==2.17.2
      - zict==3.0.0
      - zipp==3.18.1
