import warnings
warnings.filterwarnings('ignore')

import cellcharter as cc

import anndata as ad
import squidpy as sq
import scanpy as sc

import numpy as np
import pandas as pd
import os

import re
import json

import seaborn as sns
from matplotlib import pyplot as plt
from matplotlib.colors import ListedColormap
from cycler import cycler



# --------------------------------------------------------------------------------
# File I/O Setup
# --------------------------------------------------------------------------------

# OS X Laptop
#FILEPATHBASE = '/Users/mmd47/Library/CloudStorage/GoogleDrive-mmd47@yale.edu/My Drive/DiStasio Lab/DiStasio Lab Share/'

# Fedora Desktop
# conda activate cellcharter-env
FILEPATHBASE = '/home/mdistasio/YaleGoogleDrive/DiStasio Lab/DiStasio Lab Share/'


# --------------------------------------------------------------------------------

SAVEDATA = True
SAVEFIGS = True
if SAVEFIGS:
    IMGDIR = os.path.join(FILEPATHBASE,'02 Analysis', 'annData_ManualAnnotate', 'img', 'tmp')

# --------------------------------------------------------------------------------
# Load datasets (generated by IntegrateHarmony.py)
# --------------------------------------------------------------------------------
filename = os.path.join(FILEPATHBASE,'02 Analysis', 'annData_ManualAnnotate', 'calc', 'retinas_all_integrated_harmony_unfiltered.h5ad')
print("Loading Data from: " + filename + ' ...')
retinas_all = ad.read_h5ad(filename)

# Load the single nucleus RNA Seq data
filename_sn = os.path.join(FILEPATHBASE,'02 Analysis', 'annData_ManualAnnotate', 'calc', 'retina_sn_combined.h5ad')
print('Loading snRNAseq data from' + filename_sn + ' ...')
retinas_sn = ad.read_h5ad(filename_sn)
print('Done')

SampleKey = retinas_all.uns["SampleKey"]
Samples = list(retinas_all.obs['dataset'].cat.categories)

# --------------------------------------------------------------------------------
# Imputation from snRNAseq data
# --------------------------------------------------------------------------------

import scvi
from scvi.external import GIMVI
from scipy import sparse

# Fit an scVI model to the spatial data
print('Fitting an scVI model to the spatial data...')
scvi.model.SCVI.setup_anndata(retinas_all, layer="counts", batch_key="dataset")
model = scvi.model.SCVI(retinas_all, n_layers=2, n_latent=30, gene_likelihood="nb")
model.train(early_stopping=True, enable_progress_bar=True)

SCVI_LATENT_KEY = "X_scVI"
retinas_all.obsm[SCVI_LATENT_KEY] = model.get_latent_representation().astype(np.float32)

SCVI_NEIGHBORS_KEY = "neighbors_scVI"
sc.pp.neighbors(retinas_all, use_rep=SCVI_LATENT_KEY, key_added=SCVI_NEIGHBORS_KEY)
sc.tl.leiden(retinas_all, key_added="leiden_scVI", neighbors_key=SCVI_NEIGHBORS_KEY)

SCVI_MDE_KEY = "X_scVI_MDE"
retinas_all.obsm[SCVI_MDE_KEY] = scvi.model.utils.mde(retinas_all.obsm[SCVI_LATENT_KEY])

sc.pl.embedding(
    retinas_all,
    basis=SCVI_MDE_KEY,
    color=["batch", "leiden"],
    frameon=False,
    ncols=1,
)
retinas_all.layers['counts_scvi'] = sparse.csr_matrix(model.posterior_predictive_sample())
print('Done fitting an scVI model to the spatial data. Added retinas_all.layers[\'counts_scvi\']')



print('Fitting GIMVI model to the single cell and spatial data...')
# Copy the data for the imputation
st_adata = retinas_all.copy()
sc_adata = retinas_sn.copy()

# filter genes to be the same on the spatial data
intersect = np.intersect1d(sc_adata.var_names, st_adata.var_names)
st_adata = st_adata[:, intersect].copy()
sc_adata = sc_adata[:, intersect].copy()


# setup_anndata for spatial and sequencing data
GIMVI.setup_anndata(st_adata, layer="counts", batch_key="dataset")
GIMVI.setup_anndata(sc_adata, layer="counts", labels_key="CellType")

model = GIMVI(sc_adata, st_adata)
model.train(max_epochs=200, early_stopping=True, enable_progress_bar=True)

# get the latent representations for the sequencing and spatial data
_, imputed = model.get_imputed_values(normalized=True)

def transform(data):
    return np.log(1 + 100 * data)

retinas_all[:,st_adata.var_names] = transform(imputed)

# Arrange samples in space
retinas_all.obsm['X_spatial_fov'] = retinas_all.obsm['X_spatial'].copy()
y_max_p = [np.max(retinas_all[retinas_all.obs['dataset']==Samples[r]].obsm['X_spatial'][:,1]) for r in np.arange(1,len(Samples))]
y_offsets = np.append(0,np.cumsum(y_max_p))
for r in np.arange(1,len(Samples)):
    retinas_all.obsm['X_spatial_fov'][retinas_all.obs['dataset']==Samples[r],1] = retinas_all.obsm['X_spatial_fov'][retinas_all.obs['dataset']==Samples[r],1] + y_offsets[r]

# --------------------------------------------------------------------------------
# Compute Neighborhood Graph
# --------------------------------------------------------------------------------
sq.gr.spatial_neighbors(retinas_all, coord_type='generic', delaunay=True, spatial_key='X_spatial_fov')
cc.gr.remove_long_links(retinas_all)
cc.gr.aggregate_neighbors(retinas_all, n_layers=3, use_rep='X_scVI', out_key='X_cellcharter', sample_key='batch')


# --------------------------------------------------------------------------------
# Cluster
# --------------------------------------------------------------------------------
n_clusters = 21

gmm = cc.tl.Cluster(
    n_clusters=n_clusters, 
    random_state=12345,
    # If running on GPU
    trainer_params=dict(accelerator='gpu', devices=1)
)
gmm.fit(retinas_all, use_rep='X_cellcharter')
retinas_all.obs['spatial_cluster'] = gmm.predict(retinas_all, use_rep='X_cellcharter')


# --------------------------------------------------------------------------------
# Use marker genes to establish cluster labels
# --------------------------------------------------------------------------------
with open(os.path.join(FILEPATHBASE,'02 Analysis/annData_ManualAnnotate/data/retinal_celltype_gates.json')) as f:
    gates = json.load(f)

sc.tl.rank_genes_groups(retinas_all, 'spatial_cluster', use_raw=True)

marker_genes = {}
for item in gates:
    cell_type = item['cell']
    gene_list = [gene['gene'] for gene in item['gates']]
    marker_genes[cell_type] = gene_list
ov = sc.tl.marker_gene_overlap(retinas_all, marker_genes)


spatial_cluster_label_key = {0 : 'Photoreceptor',
                             1 : 'RGC',
                             2 : 'Vascular',
                             3 : 'Other',
                             4 : 'Astrocyte',
                             5 : 'Other',
                             6 : 'Photoreceptor',
                             7 : 'Muller glia',
                             8 : 'Muller glia',
                             9 : 'Bipolar',
                             10: 'Vascular',
                             11: 'RGC',
                             12: 'Muller glia',
                             13: 'Other',
                             14: 'Photoreceptor',
                             15: 'Other',
                             16: 'RPE',
                             17: 'Photoreceptor',
                             18: 'RPE',
                             19: 'Photoreceptor',
                             20: 'Other'}

retinas_all.obs['spatial_cluster_label'] = retinas_all.obs['spatial_cluster'].map(spatial_cluster_label_key)

fig, ax = plt.subplots(1, 1, figsize=(10,8))
sns.heatmap(ov, ax=ax, annot=True)


# --------------------------------------------------------------------------------
# Save
# --------------------------------------------------------------------------------
if SAVEDATA:
    # Save
    filename_out = os.path.join(FILEPATHBASE,'02 Analysis', 'annData_ManualAnnotate', 'calc', 'retinas_all_unfiltered_snRNAseq_imputed_GIMVI.h5ad')
    retinas_all.write_h5ad(filename_out)
    print('Saved ' + filename_out)

    model.save(dir_path=os.path.join(FILEPATHBASE,'02 Analysis', 'annData_ManualAnnotate', 'calc','GIMVI_model'), 
                  prefix='retinas_all_unfiltered_snRNAseq_imputation',
                  overwrite=True)

if SAVEFIGS:
    n_clusters = len(retinas_all.obs['spatial_cluster'].cat.categories)
    filename_out = os.path.join(IMGDIR, 'AllSamples_GIMVI_CellCharter_' + str(n_clusters) + '_Clusters_markermatrix.png')
    fig.savefig(filename_out, dpi=300)
    print('Saved: ' + filename_out)
    filename_out = os.path.join(IMGDIR, 'AllSamples_GIMVI_CellCharter_' + str(n_clusters) + '_Clusters_markermatrix.svg')
    fig.savefig(filename_out, dpi=300)
    print('Saved: ' + filename_out)


# --------------------------------------------------------------------------------
# Plotting
# --------------------------------------------------------------------------------

# --------------------------------------------------
# Plot of spatial scatter montage colored by cluster label
groups = np.array(sorted(np.unique(retinas_all.obs['spatial_cluster_label'])))
nGroupsToColor = len(groups) 
spect = plt.cm.tab10.resampled(nGroupsToColor)
newcolors = spect(np.linspace(0,0.5,nGroupsToColor))
newpalette = ListedColormap(newcolors)
color_cycler = cycler(color=newpalette.colors)

nRow = 3
nCol = int(np.ceil(len(Samples)/3))
fig, axs = plt.subplots(nRow, nCol, figsize=(40,30))
for r in np.arange(len(Samples)):
    ax = axs.reshape(-1)[r]
    ss = 1
    sq.pl.spatial_scatter(retinas_all[retinas_all.obs['dataset']==Samples[r]],
                          color='spatial_cluster_label',
                          size=ss,
                          shape=None,
                          groups=groups,
                          ax=ax)
    #palette=newpalette)
    ax.set_title(SampleKey[Samples[r]])

for ax in axs.reshape(-1):
    ax.set_xlabel('')
    ax.set_ylabel('')
    ax.axis('off')
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['bottom'].set_visible(False)
    ax.spines['left'].set_visible(False)
#    try:
#        ax.get_legend().remove()
#    except:
#        pass

fig.tight_layout()

fig.set_facecolor('k')
for text in fig.findobj(match=lambda x: isinstance(x, plt.Text)):
    if hasattr(text, 'set_color'):
        text.set_color('white')

#labels_handles = {  label: handle for ax in fig.axes for handle, label in zip(*ax.get_legend_handles_labels())    }
#fig.legend( labels_handles.values(), labels_handles.keys(), loc = "lower right", ncol=3)


if SAVEFIGS:
    n_clusters = len(retinas_all.obs['spatial_cluster'].cat.categories)
    filename_out = os.path.join(IMGDIR, 'AllSamples_GIMVI_CellCharter_' + str(n_clusters) + '_Clusters_006_typelabels.png')
    fig.savefig(filename_out, dpi=300)
    print('Saved: ' + filename_out)
    filename_out = os.path.join(IMGDIR, 'AllSamples_GIMVI_CellCharter_' + str(n_clusters) + '_Clusters_006_typelabels.svg')
    fig.savefig(filename_out, dpi=300)
    print('Saved: ' + filename_out)
# --------------------------------------------------
