#!/usr/bin/env python

# Preprocess.py
# Part of anndata_manualAnnotate for processing spatial omics data
# Marcello DiStasio
# Oct 2023

import warnings
warnings.filterwarnings('ignore')


import anndata as ad
import squidpy as sq
import scanpy as sc
import scvi
from scvi.model import CondSCVI, DestVI

import numpy as np
import os

from matplotlib import pyplot as plt
from matplotlib.colors import ListedColormap
from cycler import cycler

# --------------------------------------------------------------------------------
# Edit this path
# --------------------------------------------------------------------------------
#FILEPATHBASE = '/Users/mmd47/Library/CloudStorage/GoogleDrive-mmd47@yale.edu/My Drive/DiStasio Lab/DiStasio Lab Share/'
FILEPATHBASE = '/home/mdistasio/YaleGoogleDrive/DiStasio Lab/DiStasio Lab Share/'


# --------------------------------------------------------------------------------
SAVEFIGS = True
if SAVEFIGS:
    IMGDIR = os.path.join(FILEPATHBASE,'02 Analysis', 'annData_ManualAnnotate', 'img')



# --------------------------------------------------------------------------------
# Load concatenated datasets (generated by Preprocess.py
# --------------------------------------------------------------------------------
filename = os.path.join(FILEPATHBASE,'02 Analysis', 'annData_ManualAnnotate', 'calc', 'retinas_all.h5ad')
print("Loading Data from: " + filename)
retinas_all = ad.read_h5ad(filename)

retinas_all.obs['batch'] = retinas_all.obs['dataset']
retinas_all.obs['batch'][retinas_all.obs['batch'] == 'R2'] = 'R1'

retinas_all.raw = retinas_all  # keep full dimension safe 

print('Filtering for highly variable genes')
sc.pp.filter_genes(
    retinas_all,
    min_cells=20)
    
sc.pp.highly_variable_genes(
    retinas_all,
    n_top_genes=3000,
    subset=True,
    layer="counts",
    flavor="seurat_v3")

print("Done")

# --------------------------------------------------------------------------------
# Batch correction with Harmony
# (must run
# pip install harmonypy
# first)
# --------------------------------------------------------------------------------
print('Batch Correction with Harmony...')

sc.tl.pca(retinas_all)
sc.external.pp.harmony_integrate(retinas_all, key='dataset')



# --------------------------------------------------------------------------------
# Clustering
# --------------------------------------------------------------------------------

sc.pp.neighbors(retinas_all, n_neighbors=20, n_pcs=30, use_rep='X_pca_harmony')
sc.tl.leiden(retinas_all)
sc.tl.paga(retinas_all)
sc.pl.paga(retinas_all, plot=False)
sc.tl.umap(retinas_all, init_pos='paga')

# --------------------------------------------------------------------------------
# Save concatenated data
# --------------------------------------------------------------------------------
out_filename = os.path.join(FILEPATHBASE,'02 Analysis', 'annData_ManualAnnotate', 'calc', 'retinas_all_integrated_harmony.h5ad')
retinas_all.write(out_filename)

print('Saved integrated data to: ' + out_filename)


# --------------------------------------------------------------------------------
# Figure output
# --------------------------------------------------------------------------------

if SAVEFIGS:

    SampleKey = retinas_all.uns["SampleKey"]

    nGroupsToPlot = 10
    groups = sorted(np.unique(retinas_all.obs['leiden']), key=lambda x: int(x))[0:nGroupsToPlot]

    spect = plt.cm.tab10.resampled(nGroupsToPlot)
    newcolors = np.flip(spect(np.linspace(0,1,nGroupsToPlot)), axis=0)
    newpalette = ListedColormap(newcolors)
    color_cycler = cycler(color=newpalette.colors)
    
    # Fig for UMAP embedding
    fig, axx = plt.subplots(1, 2, figsize=(15,8),  gridspec_kw={'wspace': 1})
    sc.pl.umap(retinas_all, color="leiden", size=3, ax=axx[0], palette=color_cycler, groups=groups, show=False)
    sc.pl.umap(retinas_all, color="dataset", size=3, ax=axx[1], show=False)
    for ax in axx:
        ax.set_title('Harmony Combined Retinas')
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)
        ax.spines['bottom'].set_visible(False)
        ax.spines['left'].set_visible(False)


    for img_ext in ['png','svg']:
        fig_filename = os.path.join(IMGDIR, 'UMAP_Harmony_-_.' + img_ext)
        fig.savefig(fig_filename, dpi=300)    
        print('Saved figure: ' + fig_filename)

    

    # Spatial Scatter Montage
    Samples = list(retinas_all.obs['dataset'].cat.categories)

    nRow = 2
    nCol = int(np.ceil(len(Samples)/2))
    fig, axs = plt.subplots(nRow, nCol, figsize=(35,20))
    for r in np.arange(len(Samples)):
        ax = axs.reshape(-1)[r]
        ss = 10
        sq.pl.spatial_scatter(retinas_all[retinas_all.obs['dataset']==Samples[r]], 
                              color='leiden', 
                              groups=groups,
                              size=ss, 
                              shape=None, 
                              ax=ax, 
                              palette=newpalette)
        ax.set_title(SampleKey[Samples[r]])
        ax.set_xlabel('')
        ax.set_ylabel('')
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)
        ax.spines['bottom'].set_visible(False)
        ax.spines['left'].set_visible(False)
        ax.get_legend().remove()
    fig.tight_layout()

    labels_handles = {  label: handle for ax in fig.axes for handle, label in zip(*ax.get_legend_handles_labels())    }
    fig.legend( labels_handles.values(), labels_handles.keys(), loc = "upper right", ncol=3)

    
    for img_ext in ['png','svg']:
        fig_filename = os.path.join(IMGDIR, 'Spatial_Harmony_-_.' + img_ext)
        fig.savefig(fig_filename, dpi=300)    
        print('Saved figure: ' + fig_filename)

        
print("Complete! Exiting.")


